### ISSUE TITLE
Home page(How it Works & ADD YOUR PROPERTY): Featured image won't display on IE9 browser.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/List-Me#16]
![2015-11-27_0950-ie9](https://cloud.githubusercontent.com/assets/13309730/11441026/06ab6610-952e-11e5-8a08-09e070a12b48.png)

**Comment by mahender-sowedane** [comment]
Layout is broken, issue not fixed properly

![2015-12-10_1134](https://cloud.githubusercontent.com/assets/13309730/11708146/1b457292-9f32-11e5-9516-24edcfb88836.png)

**Comment by isaq-titan** [comment]
IE9 does not support the Image with Gradient Background style.
