### ISSUE TITLE
Header section: Sub-menu's are not working properly.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/List-Me#3]
1st and 2nd level sub-menus not displayed.
When hover on main menu item all are displaying, have a look this screen.

![untitled-1](https://cloud.githubusercontent.com/assets/13309730/11436005/737ee24e-9506-11e5-8038-916d3fc7f6a7.png)

**Comment by mahender-sowedane** [comment]
Still not fixed properly.

![2015-12-09_1828](https://cloud.githubusercontent.com/assets/13309730/11685940/cb9fb656-9ea2-11e5-8bb6-46de8f952e55.png)

**Comment by ermatitan** [comment]
This issue re -occurs. See screenshot below:

![image](https://cloud.githubusercontent.com/assets/12791909/12083118/f51b12a2-b2d7-11e5-8426-9ed29cf18e2a.png)
