### ISSUE TITLE
Add Your Property page: Form fields alignment is distorting on all devices.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/List-Me#45]
![screenshot_2015-11-27-10-03-01](https://cloud.githubusercontent.com/assets/13309730/11469056/dd3077f0-9779-11e5-899f-18765be7d7c8.png)

**Comment by mahender-sowedane** [comment]
Not fixed and also form is not implemented as per psd.

![untitled-1](https://cloud.githubusercontent.com/assets/13309730/11709523/600e7426-9f3e-11e5-86b8-e5d784e37e4c.png)

**Comment by isaq-titan** [comment]
It is updated by Project Manager
