### ISSUE TITLE
Add your property fields has is not the same with the design

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/List-Me#70]
![image](https://cloud.githubusercontent.com/assets/12791909/12084234/93c398ee-b2eb-11e5-82f8-52a68da16a68.png)

**Comment by saif-titan** [comment]
please  refer to carin comments
![27- list me - qa titan digital 2016-01-11 15-17-19](https://cloud.githubusercontent.com/assets/13676221/12230502/03bfd9fe-b806-11e5-85d9-5897d064ebdb.png)
