### ISSUE TITLE
Agent Registration button should read as send instead of subscribe now as per design

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/List-Me#71]
![image](https://cloud.githubusercontent.com/assets/12791909/12084287/62c7ad9c-b2ec-11e5-9184-bdc7c3ab48be.png)

**Comment by saif-titan** [comment]
please refer to carin bowman  comment
![27- list me - qa titan digital 2016-01-11 15-17-19](https://cloud.githubusercontent.com/assets/13676221/12230453/94da5b22-b805-11e5-8a9b-d882782a5c8b.png)

Send button renamed - Agent Registration Page.
